name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ inputs.name }}!"
